services:
  mysql-db:
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: definitions
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysql -ptest123 -e 'select 1'"]
      interval: 5s
      retries: 50
  api:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    build: .
    ports:
      - "8080:8080"
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/definitions
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test123
    depends_on:
      mysql-db:
        condition: service_healthy